baseURL = "https://dayio.dev/"
languageCode = "en-us"
title = "Dayio.dev"
theme = "archie"
copyright = "© Dayio"

# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[pagination]
  pagerSize = 5 # articles per page

[params]
	mode="toggle"
	useCDN=false
	subtitle = "Exploring tech from the cloud down to the hardware level"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/dayio"

[[menu.main]]
name = "~/"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4
